/**
 * scripts/setup.js
 * ─────────────────────────────────────────────────
 * Run once after cloning / first install:
 *   npm run setup
 *
 * Does:
 *  1. Generates a .env with a random JWT_SECRET
 *  2. Creates the data/ directory
 *  3. Runs all DB migrations
 *  4. Asks whether to seed demo data
 *  5. Prints the server URL + QR
 * ─────────────────────────────────────────────────
 */

'use strict';

const fs      = require('fs');
const path    = require('path');
const os      = require('os');
const crypto  = require('crypto');
const readline= require('readline');

const ROOT = path.join(__dirname, '..');

// ── helpers ───────────────────────────────────────
function ask(q) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(r => rl.question(q, a => { rl.close(); r(a.trim()); }));
}

function getLocalIp() {
  for (const ifaces of Object.values(os.networkInterfaces()))
    for (const i of ifaces)
      if (i.family === 'IPv4' && !i.internal) return i.address;
  return 'localhost';
}

// ── 1. .env ───────────────────────────────────────
const envPath   = path.join(ROOT, '.env');
const envExample= path.join(ROOT, '.env.example');

if (!fs.existsSync(envPath)) {
  const secret = crypto.randomBytes(48).toString('hex');
  const port   = '3000';
  const envContent = `# Auto-generated by setup.js\nJWT_SECRET=${secret}\nPORT=${port}\nNODE_ENV=production\nAUTO_BACKUP=true\nMAX_BACKUPS=10\nBACKUP_EVERY=21600000\n`;
  fs.writeFileSync(envPath, envContent);
  console.log('✅  .env created with secure JWT_SECRET');
} else {
  console.log('ℹ️   .env already exists — skipping');
}

// ── 2. data/ dir ─────────────────────────────────
const dataDir = path.join(ROOT, 'data');
fs.mkdirSync(dataDir, { recursive: true });
fs.mkdirSync(path.join(dataDir, 'backups'), { recursive: true });
console.log('✅  data/ directory ready');

// ── 3. Load env + run migrations ─────────────────
require('dotenv').config({ path: envPath });
require('../db/migrate').migrate();
console.log('✅  Database migrations applied');

// ── 4. Optional seed ─────────────────────────────
(async () => {
  const ans = await ask('\n🌱  Load demo data? (طلاب + معيد تجريبي) [y/N]: ');
  if (ans.toLowerCase() === 'y') {
    require('../db/seed');
    // seed.js calls process.exit(0) itself
  } else {
    const ip   = getLocalIp();
    const port = process.env.PORT || 3000;
    console.log('\n' + '═'.repeat(52));
    console.log('  ✅  Setup complete!');
    console.log('─'.repeat(52));
    console.log(`  Run:     npm start`);
    console.log(`  URL:     http://${ip}:${port}`);
    console.log(`  QR:      http://${ip}:${port}/qr`);
    console.log('═'.repeat(52) + '\n');
    process.exit(0);
  }
})();
